arm64v8 package optimization

diff --git a/.github/workflows/build-arm64v8.yml b/.github/workflows/build-arm64v8.yml
--- a/.github/workflows/build-arm64v8.yml
+++ b/.github/workflows/build-arm64v8.yml
@@ -24,8 +24,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     outputs:
-      deviceName: ${{ env.DEVICE_NAME }}
-      fileDate: ${{ env.FILE_DATE }}
+      PRE_PACKAGE_ARTIFACT_ID: ${{ steps.rootfsUpload.outputs.artifact-id }}
 
     steps:
     - name: Before freeing up disk space
@@ -145,7 +144,7 @@ jobs:
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
 
     - name: Check space usage
-      if: ${{ !cancelled() }}
+      if: (!cancelled())
       run: df -hT
 
     - name: Upload bin directory
@@ -164,72 +163,51 @@ jobs:
         echo "FIRMWARE=$PWD" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT
 
+    - name: Find Rootfs File
+      id: findRootfs
+      if: steps.organize.outputs.status == 'success' && !cancelled()
+      run: |
+        set -euo pipefail
+
+        ROOT_DIR="${{ env.FIRMWARE }}"
+        echo "🔎 Searching for *rootfs.tar.gz in: $ROOT_DIR"
+
+        ROOTFS_FILE=$(find "$ROOT_DIR" -type f -name '*rootfs.tar.gz' -print -quit || true)
+
+        if [[ -z "${ROOTFS_FILE:-}" ]]; then
+          echo "❌ rootfs not found in $ROOT_DIR"
+          echo "📂 Listing files in $ROOT_DIR"
+          ls -al "$ROOT_DIR" || true
+          echo "status=not_found" >> $GITHUB_OUTPUT
+          exit 0
+        fi
+
+        echo "✅ Found: $ROOTFS_FILE"
+        BASENAME=$(basename -- "$ROOTFS_FILE")
+        echo "ROOTFS_FILE=$ROOTFS_FILE" >> $GITHUB_OUTPUT
+        echo "BASENAME=$BASENAME" >> $GITHUB_OUTPUT
+        echo "status=success" >> $GITHUB_OUTPUT
+
     - name: Upload firmware directory
       uses: actions/upload-artifact@main
       if: steps.organize.outputs.status == 'success' && !cancelled()
       with:
         name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-        path: ${{ env.FIRMWARE }}
+        path: |
+          ${{ env.FIRMWARE }}
+          !${{ steps.findRootfs.outputs.ROOTFS_FILE }}
 
-    # - name: Upload firmware to cowtransfer
-    #   id: cowtransfer
-    #   if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
-    #   run: |
-    #     curl -fsSL git.io/file-transfer | sh
-    #     ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
-    #     echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
-    #     echo "url=$(cat cowtransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_OUTPUT
-
-    # - name: Upload firmware to WeTransfer
-    #   id: wetransfer
-    #   if: steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
-    #   run: |
-    #     curl -fsSL git.io/file-transfer | sh
-    #     ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
-    #     echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
-    #     echo "url=$(cat wetransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_OUTPUT
-
-    # - name: Generate release tag
-    #   id: tag
-    #   if: env.UPLOAD_RELEASE == 'true' && !cancelled()
-    #   run: |
-    #     echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
-    #     touch release.txt
-    #     [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
-    #     [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
-    #     echo "status=success" >> $GITHUB_OUTPUT
-
-    # - name: Upload firmware to release
-    #   uses: softprops/action-gh-release@v1
-    #   if: steps.tag.outputs.status == 'success' && !cancelled()
-    #   env:
-    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    #   with:
-    #     tag_name: ${{ steps.tag.outputs.release_tag }}
-    #     body_path: release.txt
-    #     files: ${{ env.FIRMWARE }}/*
-
-    # - name: Delete workflow runs
-    #   uses: Mattraks/delete-workflow-runs@v2
-    #   with:
-    #     retain_days: 1
-    #     keep_minimum_runs: 3
-
-    # - name: Remove old Releases
-    #   uses: dev-drprasad/delete-older-releases@v0.1.0
-    #   if: env.UPLOAD_RELEASE == 'true' && !cancelled()
-    #   with:
-    #     keep_latest: 3
-    #     delete_tags: true
-    #   env:
-    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Upload Rootfs File
+      id: rootfsUpload
+      uses: actions/upload-artifact@main
+      if: steps.findRootfs.outputs.status == 'success' && !cancelled()
+      with:
+        name: ${{ steps.findRootfs.outputs.BASENAME }}
+        path: ${{ steps.findRootfs.outputs.ROOTFS_FILE }}
 
   pack:
     runs-on: ubuntu-latest
     needs: [build]
-    env:
-      DEVICE_NAME: ${{ needs.build.outputs.deviceName }}
-      FILE_DATE: ${{ needs.build.outputs.fileDate }}
     strategy:
       fail-fast: false
       matrix:
@@ -237,13 +215,24 @@ jobs:
         PACK_KERNEL_VERSION_NAME: ['6.6.y', '6.12.y']
 
     steps:
+      - name: Freeing up disk space
+        uses: easimon/maximize-build-space@master
+        with: 
+          root-reserve-mb: 3072
+          swap-size-mb: 1
+          remove-dotnet: 'true'
+          remove-android: 'true'
+          remove-haskell: 'true'
+          remove-codeql: 'true'
+          remove-docker-images: 'true'
+
       - name: Checkout
         uses: actions/checkout@main
 
       - name: Initialization environment
         env:
           DEBIAN_FRONTEND: noninteractive
-        if: ${{ needs.build.result }} == 'success' && !cancelled()
+        if: needs.build.result == 'success' && !cancelled()
         run: |
           sudo -E apt-get -qq update
           sudo -E apt-get -qq full-upgrade
@@ -254,23 +243,23 @@ jobs:
           /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules
           sudo timedatectl set-timezone "$TZ"
 
-      - name: Download Artifact Target
+      - name: Download Rootfs File
         uses: actions/download-artifact@main
         id: downloadArtifact
-        if: ${{ needs.build.result }} == 'success' && !cancelled()
+        if: needs.build.result == 'success' && !cancelled()
         with:
-          name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
+          artifact-ids: ${{ needs.build.outputs.PRE_PACKAGE_ARTIFACT_ID }}
           path: ${{ env.PACK_DOWNLOAD_TARGET_PATH }}
 
       - name: Find Rootfs File
         id: findRootfs
-        if: ${{ steps.downloadArtifact.outcome }} == 'success' && !cancelled()
+        if: steps.downloadArtifact.outcome == 'success' && !cancelled()
         run: |
           set -euo pipefail
           ROOT_DIR="${{ env.PACK_DOWNLOAD_TARGET_PATH }}"
           echo "🔎 Searching for *rootfs.tar.gz in: $ROOT_DIR"
           ROOTFS_FILE=$(find "$ROOT_DIR" -type f -name '*rootfs.tar.gz' -print -quit || true)
-          if [[ -z "${ROOTFS_FILE:-}" ]]; then
+          if [[ -z "${ROOTFS_FILE:-}" || ! -f "$ROOTFS_FILE" ]]; then
             echo "❌ rootfs not found in $ROOT_DIR"
             echo "📂 Listing files in $ROOT_DIR"
             ls -al "$ROOT_DIR"
@@ -283,7 +272,7 @@ jobs:
 
       - name: Package OpenWrt Firmware
         uses: unifreq/openwrt_packit@master
-        if: ${{ steps.findRootfs.outputs.status }} == 'success' && !cancelled()
+        if: steps.findRootfs.outputs.status == 'success' && !cancelled()
         env:
           OPENWRT_ARMSR: ${{ steps.findRootfs.outputs.rootfsFile }}
           PACKAGE_SOC: ${{ matrix.PACK_PACKAGE_SOC }}
@@ -293,17 +282,18 @@ jobs:
 
       - name: Organize files
         id: organize
-        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
+        if: env.PACKAGED_STATUS == 'success' && !cancelled()
         run: |
           cd ${{ env.PACKAGED_OUTPUTPATH }}
           rm -rf *rootfs.tar.gz *rootfs.tar.gz.sha
+          echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
           echo "status=success" >> $GITHUB_OUTPUT
 
       - name: Upload firmware directory
         uses: actions/upload-artifact@main
-        if: ${{ steps.organize.outputs.status }} == 'success' && !cancelled()
+        if: steps.organize.outputs.status == 'success' && !cancelled()
         with:
-          name: OpenWrt_firmware_${{ matrix.PACK_PACKAGE_SOC }}_${{ matrix.PACK_KERNEL_VERSION_NAME }}${{ env.FILE_DATE }}
+          name: OpenWrt_firmware_${{ matrix.PACK_PACKAGE_SOC }}_${{ matrix.PACK_KERNEL_VERSION_NAME }}_${{ steps.organize.outputs.timestamp }}
           path: ${{ env.PACKAGED_OUTPUTPATH }}
 
       - name: Delete workflow runs
